name: Publish .NET Framework 4.8 Package

on:
  push:
    branches:
      - master  # or the branch you want to use




jobs:
  publish:
    runs-on: windows-latest
    env:  # Define env variables at the job level
      build_projectName: "DCFHW"
      build_workspace: "DEV/DCFHW"
      build_solutionPath: "DEV/DCFHW/DCFHW.sln"
      build_configuration: Release
      build_run_id: ${{ github.run_id }}
      build_stagingPath: ./ArtifactStaging
      build_artifactPath: ./DEV/DCFHW/DCFHW/ArtifactStaging
      vswarepath: "C:\\Program Files\\vswhere"

    steps:
      - name: Checkout code
        run: |
            $url = "https://github.com/microsoft/vswhere/releases/latest/download/vswhere.exe" 
            $output = "${{ github.workspace }}\myfolder\vswhere.exe"
            
            New-Item -ItemType Directory -Path (Split-Path $output) -Force 
            Invoke-WebRequest -Uri $url -OutFile $output
            echo "Stqp11"
            
            echo $output
            
            #shell: pwsh

        # Below to try After come Back!!
      - name: Set an environment variable   
        run: echo "MY_VAR=HelloWorld" >> $GITHUB_ENV

      - name: Print GITHUB_ENV path
        run: echo "GITHUB_ENV path is $GITHUB_ENV"

      - name: Print contents of GITHUB_ENV
        run: cat $GITHUB_ENV
             
  
     
   

        
