name: Publish .NET Framework 4.8 Package

on:
  push:
    branches:
      - master  # or the branch you want to use

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Framework 4.8
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        run: nuget restore WebApp1.sln

      - name: Build project
        run: msbuild WebApp1.csproj /p:Configuration=Release

      - name: Pack .NET Framework 4.8 project
        run:  nuget pack MyDb2Package.nuspec -OutputDirectory ./output

      - name: Github Owner Details
        run: echo  ${{ github.repository_owner }}
        
      - name: Configure npm to use GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.API_SECRET }}" > ~/.npmrc
          echo "@OWNER:registry=https://npm.pkg.github.com" >> ~/.npmrc
        env:
          OWNER: ${{ github.repository_owner }}
     

      - name: Publish to GitHub Packages
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.API_SECRET }}
        run: nuget push "./output/*.nupkg" -Source "https://nuget.pkg.github.com/MTUser/index.json" -ApiKey ${{ secrets.API_SECRET }}

        
