name: Publish .NET Framework 4.8 Package

on:
  push:
    branches:
      - master  # or the branch you want to use

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Framework 4.8
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        run: nuget restore WebApp1.sln

      - name: Build project
        run: msbuild WebApp1.csproj /p:Configuration=Release

      - name: Pack .NET Framework 4.8 project
        run:  nuget pack MyDb2Package.nuspec -OutputDirectory ./output

      - name: Github Owner Details
        run: echo  ${{ github.repository_owner }}
        
      - name: Authenticate with GitHub Packages
        run: dotnet nuget add source --username MTUser --password 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 --store-password-in-clear-text --name github "https://nuget.pkg.github.com/MTUser/index.json"

      - name: List all Nuget File
        run: ls -l ./output/
    

      - name: Publish to GitHub Packages
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.API_SECRET }}
        run: nuget push "./output/*.nupkg" -Source "https://nuget.pkg.github.com/MTUser/index.json" -ApiKey ${{ secrets.API_SECRET }}

        
