name: Publish .NET Framework 4.8 Package

on:
  push:
    branches:
      - master  # or the branch you want to use

jobs:
  publish:
    runs-on: windows-latest
    env:  # Define env variables at the job level
      build_projectName: "DCFHW"
      build_workspace: "DEV/DCFHW"
      build_solutionPath: "DEV/DCFHW/DCFHW.sln"
      build_configuration: Release
      build_run_id: ${{ github.run_id }}
      build_stagingPath: ./ArtifactStaging
      build_artifactPath: ./DEV/DCFHW/DCFHW/ArtifactStaging
      vswarepath: "C:\\Program Files\\vswhere"
      GLOBAL_VAR: "This is a global variable"
